# Generated by Django 3.2.18 on 2024-03-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_rental_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_book_returned',
            field=models.BooleanField(default=False),
        ),
    ]
