# Generated by Django 3.2.18 on 2024-03-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_rental_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlogs',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminlogs',
            name='action_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
