# Generated by Django 3.2.18 on 2024-03-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20240316_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='first_publish_date',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='fee',
        ),
    ]
