# Generated by Django 3.2.18 on 2024-03-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240316_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='updated_at',
        ),
    ]
